<a href="https://colab.research.google.com/github/ankitajaswal/Cmpe255/blob/main/AJ's_Copy_of_testing_ground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split


In [3]:
np.set_printoptions(linewidth=114)

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
input_file = "/content/drive/Shareddrives/CMPE 255 - Team Project/A_Z Handwritten Data.csv"
df = pd.read_csv(input_file, header = 0)

KeyboardInterrupt: ignored

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372450 entries, 0 to 372449
Columns: 785 entries, 0 to 0.648
dtypes: int64(785)
memory usage: 2.2 GB


In [ ]:
#split data into train and test set
train, test = train_test_split(df, test_size=0.20)

#save both train and test to their individial csv files
train.to_csv('train.csv', index = False)
test.to_csv('test.csv', index = False)

### Preprocess: 

In [6]:
train_file = "/content/drive/Shareddrives/CMPE 255 - Team Project/train.csv"
train_df = pd.read_csv(train_file, header = 0)


In [7]:
train_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297960 entries, 0 to 297959
Columns: 785 entries, 0 to 0.648
dtypes: int64(785)
memory usage: 1.7 GB


In [32]:
#set train data
train_data = train_df.iloc[:,1:].values.astype(np.float32)
#set train labels
train_label = train_df.iloc[:,0].values.astype(np.float32)

#reshape data into a format to apply KNN model fitting
train_data = train_data.reshape(297960, 28, 28)

In [35]:
print(train_label)

[ 2. 14. 24. ... 19. 18. 15.]


In [30]:
import matplotlib.pyplot as plt
import plotly.express as px

#view some examples from the data

px.imshow(train_data[1000], color_continuous_scale='magma')

In [10]:
px.imshow(train_data[2000], color_continuous_scale='magma')

In [11]:
px.imshow(train_data[4000], color_continuous_scale='magma')

In [12]:
px.imshow(train_data[10000], color_continuous_scale='magma')

In [14]:
px.imshow(train_data[20000], color_continuous_scale='magma')

split data is shuffled and has a large variation for each captial letter alphabet. Therefore, no bias is induced. 

In [ ]:
train_df.iloc[:,0].value_counts().sort_index()

0     11074
1      6968
2     18705
3      8058
4      9234
5       937
6      4658
7      5721
8       900
9      6817
10     4460
11     9301
12     9835
13    15156
14    46266
15    15577
16     4602
17     9196
18    38778
19    18003
20    23198
21     3311
22     8657
23     5028
24     8665
25     4855
Name: 0, dtype: int64

In [ ]:
train_df.count(axis='columns')

0         785
1         785
2         785
3         785
4         785
         ... 
297955    785
297956    785
297957    785
297958    785
297959    785
Length: 297960, dtype: int64

In [ ]:
row1 = train_df.iloc[6,:].values

row1 = row1[7:784]

print(row1)
print(type(row1))
print(row1.shape)


[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0  95 255  96   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   6 219 255 211   0   0   0   0   0   0   0   7 207 177   0   0   0   0   0   0   0   0   0   0   0
   0   0   0 147 255 255 211   0   0   0   0   0   0   0 119 255 255   0   0   0   0   0   0   0   0   0   0   0
   0   0   3 189 255 255 103   0   0   0   0   0   0  46 250 255 255   0   0   0   0   0   0   0   0   0   0   0
   0   0  99 255 255 187   3   0   0   0   0   0   0 171 255 255 217   0   0   0   0   0   0   0

In [ ]:
mat1 = np.resize(row1, (28, 28))

In [ ]:
print(mat1)

[[ 16   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  29 109 192 225 172  61   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  69 184 162  55  22  88 133  62   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   8  86 193 124  22   0   0  57 154 140  36   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  85 184 107  18   0   0   0   8  95 162  59   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  28 188 136  29   0   0   0   0   0  16 116 17

In [ ]:
im = Image.fromarray(mat1.astype(np.uint8))

In [ ]:
im

In [8]:
test_file = "/content/drive/Shareddrives/CMPE 255 - Team Project/test.csv"
test_df = pd.read_csv(train_file, header = 0)

In [9]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297960 entries, 0 to 297959
Columns: 785 entries, 0 to 0.648
dtypes: int64(785)
memory usage: 1.7 GB


In [10]:
#set test data
test_data = test_df.iloc[:,1:].values
#set test labels
test_label = test_df.iloc[:,0].values

#reshape data into a format to apply KNN model fitting
test_data = test_data.reshape(297960, 28, 28)

Feed Data to KNN model